"""Core package — foundational types, config, and site definitions.

All other packages depend on core/. Core depends on nothing else in ai_crawler.
"""

from ai_crawler.core.types import (
    ProxyType,
    RenderType,
    TierSystem,
    PagePattern,
    CrawlPolicy,
    CrawlTask,
    StrategyAttempt,
    SiteMemory,
    MemoryStore,
    Product,
    product_to_item,
    CrawlerError,
    FetchError,
    BlockDetectedError,
    ProxyError,
    ProxyAuthError,
    BrowserError,
    BrowserLaunchError,
    ExtractionError,
    CaptchaError,
    CaptchaSolveError,
    RENDER_COST,
)

from ai_crawler.core.config import (
    config,
    Config,
    setup_logging,
    browser_config,
    retry_config,
    concurrency_config,
    extraction_config,
    block_detection_config,
    browser_selector_config,
    BrowserConfig,
    RetryConfig,
    ConcurrencyConfig,
    ExtractionConfig,
    BlockDetectionConfig,
    BrowserSelectorConfig,
    BOT_NAME,
    DOWNLOAD_DELAY,
    RANDOMIZE_DOWNLOAD_DELAY,
    CONCURRENT_REQUESTS_PER_DOMAIN,
    RETRY_TIMES,
    RETRY_ENABLED,
    COOKIES_ENABLED,
    AUTOTHROTTLE_ENABLED,
    AUTOTHROTTLE_START_DELAY,
    AUTOTHROTTLE_MAX_DELAY,
    AUTOTHROTTLE_TARGET_CONCURRENCY,
    RENDER_ENGINE,
    TRACE_DIR,
    OUTPUT_DIR,
    MAX_IP_RETRIES,
    RUNTIME_CONCURRENCY,
)

from ai_crawler.core.sites import (
    SUPPORTED_SITES,
    SITE_TIER_DEFAULTS,
    URL_PATTERNS,
    PATTERNS,
    DOMAIN_TO_SITE,
    infer_site_from_url,
    infer_site_from_url_or_empty,
    get_site_tier,
)
