from ai_crawler.spider.engine.captcha import CaptchaService, CaptchaDetector, CaptchaSolver, CaptchaType
from ai_crawler.spider.engine.proxy import ProxyProvider, ThorDataManager, ThorDataPool, ThorDataSession, UCProxyBridge
from ai_crawler.spider.engine.anti_bot import (
    AntiBotHandler,
    AntiBotFingerprinter,
    AntiBotFingerprint,
    BlockDetector,
    BlockType,
    Attempt,
    FetchEngineer,
)
from ai_crawler.spider.engine.core import (
    Crawler,
    Queue,
    SiteMemory,
    StrategyAttempt,
    Planner,
    CrawlResult,
    FailureOutcomeHandler,
    TraceRecorder,
    AntiBotTrace,
    TraceStore,
)
from ai_crawler.spider.engine.dynamic_thresholds import DynamicThresholdOptimizer, SiteMetrics
from ai_crawler.spider.engine.errors import (
    CrawlerError,
    FetchError,
    BlockDetectedError,
    ProxyError,
    ProxyAuthError,
    BrowserError,
    BrowserLaunchError,
    ExtractionError,
    CaptchaError,
    CaptchaSolveError,
)
from ai_crawler.spider.engine.introspection import get_hardware_fingerprint, get_system_facts
from ai_crawler.spider.engine.policy_engine import (
    ConditionalStats,
    CrawlPolicyCandidate,
    CrawlPolicyScorer,
    CrawlPolicyScore,
    CrawlPolicyStats,
    CrawlPolicyStatsStore,
)
from ai_crawler.spider.engine.recommendation import DSPyStrategyRecommender
from ai_crawler.spider.engine.telemetry import (
    detect_block_reason,
    detect_waf,
    extract_response_headers,
    generate_human_summary,
)
from ai_crawler.spider.engine.crawl_policy_generator import CrawlPolicyGenerator, policy_candidate_to_strategy
from ai_crawler.spider.coordinator import CrawlCoordinator

__all__ = [
    "AntiBotHandler",
    "AntiBotTrace",
    "BlockDetector",
    "BlockType",
    "CaptchaService",
    "CaptchaDetector",
    "CaptchaSolver",
    "CaptchaType",
    "ConditionalStats",
    "AntiBotFingerprinter",
    "AntiBotFingerprint",
    "CrawlCoordinator",
    "Crawler",
    "CrawlResult",
    "Queue",
    "DynamicThresholdOptimizer",
    "DSPyStrategyRecommender",
    "detect_block_reason",
    "detect_waf",
    "extract_response_headers",
    "FailureOutcomeHandler",
    "Attempt",
    "get_hardware_fingerprint",
    "get_system_facts",
    "generate_human_summary",
    "ConditionalStats",
    "CrawlPolicyCandidate",
    "CrawlPolicyScorer",
    "CrawlPolicyScore",
    "CrawlPolicyStats",
    "CrawlPolicyStatsStore",
    "ProxyProvider",
    "SiteMemory",
    "SiteMetrics",
    "StrategyAttempt",
    "Planner",
    "FetchEngineer",
    "TraceRecorder",
    "TraceStore",
    "CrawlPolicyGenerator",
    "policy_candidate_to_strategy",
    "ThorDataManager",
    "ThorDataPool",
    "ThorDataSession",
    "UCProxyBridge",
    "CrawlerError",
    "FetchError",
    "BlockDetectedError",
    "ProxyError",
    "ProxyAuthError",
    "BrowserError",
    "BrowserLaunchError",
    "ExtractionError",
    "CaptchaError",
    "CaptchaSolveError",
]
